server:
   port: 9411

spring:
  application:
    name: zipkin-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      cluster: elastic_prd
      hosts: http://192.168.2.79:9200  #生产环境的
      index: cloud-zipkin
      index-shards: 5
      index-replicas: 1