server:
  port: 8181

management:
  security:
    enabled: false

spring:
  cloud:
    config:
      uri: http://127.0.0.1:${config.port:8888}
      label: trunk
      name: config-demo
      profile: ${config.profile:dev}
  application:
    name: config-client
    index: ${random.long}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest