server:
  port: 8866

spring:
  application:
    name: eureka-cloud-zuul-serviceid

eureka:
  client:
    serviceUrl:
      defaultZone: http://master:8761/eureka/,http://backup:8762/eureka/

zuul:
  routes:
    demo:
      path: "/registry/**"
      serviceId: eureka-server-registry