server:
   port: 8761

eureka:
  instance:
    hostname: master
  client:
    #由于该应用为注册中心，所以设置为false,代表不向注册中心注册自己
    registerWithEureka: false
    #由于注册中心的职责就是维护服务实例，所以他不需要去检索服务
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://backup:8762/eureka/
spring:
  application:
    name: cloud-eureka-server



