server:
   port: 9400

spring:
  application:
    name: zipkin-provider


  zipkin:
    base-url: http://localhost:9411
    service:
      name: ${spring.application.name}
  sleuth:
    #监控开关
    enabled: true
    #采样率
    sampler:
      percentage: 1

