server:
   port: 8762

eureka:
  instance:
    hostname: backup
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://master:8761/eureka/
spring:
  application:
    name: cloud-eureka-server



