server:
  port: 8989

spring:
  application:
    name: eureka-cloud-hystrix-eureka

eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://master:8761/eureka/,http://backup:8762/eureka/